# Importing Libraries and Dataset

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
path = r'C:\Users\bhava\Documents\18.02.26_Instacart Basket Analysis'

In [3]:
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge.pkl'))

In [4]:
ords_prods_merge.head()

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,Unnamed: 0,product_name,aisle_id,department_id,prices,_merge
0,2539329,1,1,2,8,NaN,196,1,0,195,Soda,77,7,9.0,both
1,2539329,1,1,2,8,NaN,14084,2,0,14084,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both
2,2539329,1,1,2,8,NaN,12427,3,0,12427,Original Beef Jerky,23,19,4.4,both
3,2539329,1,1,2,8,NaN,26088,4,0,26089,Aged White Cheddar Popcorn,23,19,4.7,both
4,2539329,1,1,2,8,NaN,26405,5,0,26406,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both

In [5]:
ords_prods_merge.shape

(32404859, 15)

# Removing unnessecary column Unnamed: 0 and rewriting the name

In [6]:
ords_prods_merge = ords_prods_merge.drop(columns = ['Unnamed: 0'])

In [7]:
ords_prods_merge.head()

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,4.4,both
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,both
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both

In [8]:
# number after the colon: this indicates that the subset should include everything from the beginning of the dataframe up to that number

df = ords_prods_merge[:1000000]

In [9]:
df.shape

(1000000, 14)

In [10]:
df

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,4.4,both
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,both
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2789027,6474,2,3,8,30.0,3020,7,0,Broccoli & Apple Stage 2 Baby Food,92,18,12.9,both
999996,2789027,6474,2,3,8,30.0,35823,8,0,Complete Foaming Antibacterial Hand Soap Varie...,127,11,7.3,both
999997,2789027,6474,2,3,8,30.0,27681,9,0,Lower Sugar Instant Oatmeal Variety,130,14,3.5,both
999998,2789027,6474,2,3,8,30.0,2091,10,0,Almond Nut & Rice Cracker Snacks,78,19,6.8,both
999999,2789027,6474,2,3,8,30.0,44199,11,0,Toll House Mini Chocolate Chip Cookie Dough,105,13,2.9,both

In [11]:
def price_label(row):

  if row['prices'] <= 5:
    return 'Low-range product'
  elif (row['prices'] > 5) and (row['prices'] <= 15):
    return 'Mid-range product'
  elif row['prices'] > 15:
    return 'High range'
  else: return np.nan

In [12]:
df['price_range'] = df.apply(price_label, axis=1)

# This axis = 1 stands for “rows,” so this code essentially tells Python to apply the function to all rows within the dataframe. Conversely, axis = 0 would refer to all columns within the dataframe.

C:\Users\bhava\AppData\Local\Temp\ipykernel_22608\808061328.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_range'] = df.apply(price_label, axis=1)

In [13]:
df.head(10)

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Mid-range product
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,4.4,both,Low-range product
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Low-range product
5,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product
6,2398795,1,2,3,7,15.0,10258,2,0,Pistachios,117,19,3.0,both,Low-range product
7,2398795,1,2,3,7,15.0,12427,3,1,Original Beef Jerky,23,19,4.4,both,Low-range product
8,2398795,1,2,3,7,15.0,13176,4,0,Bag of Organic Bananas,24,4,10.3,both,Mid-range product
9,2398795,1,2,3,7,15.0,26088,5,1,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product

In [14]:
df.shape

(1000000, 15)

In [15]:
df['price_range'].value_counts(dropna = False)

price_range
Mid-range product    673183
Low-range product    314392
High range            12425
Name: count, dtype: int64

In [16]:
df['prices'].max()

99999.0

# Using loc(), you can apply the conditional logic of an if-statement to a function without explicitly creating an if-else construct
##  The difference here is that there’s no explicit if in your if-statement. Instead, it’s all been implied.

In [17]:
df.loc[df['prices'] > 15, 'price_range_loc'] = 'High-range product'

ords_prods_merge.loc[ords_prods_merge['prices'] > 15, 'price_range_loc'] = 'High-range product'

C:\Users\bhava\AppData\Local\Temp\ipykernel_22608\2108514796.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['prices'] > 15, 'price_range_loc'] = 'High-range product'

In [18]:
ords_prods_merge.loc[ (ords_prods_merge['prices'] <= 15) & (ords_prods_merge['prices'] > 5), 'price_range_loc' ] = 'Mid-range product'

In [19]:
ords_prods_merge.loc[ords_prods_merge['prices'] <= 5, 'price_range_loc'] = 'Low-range product'

In [20]:
ords_prods_merge['price_range_loc'].value_counts(dropna = False)

price_range_loc
Mid-range product     21860860
Low-range product     10126321
High-range product      417678
Name: count, dtype: int64

In [21]:
ords_prods_merge['price_range_loc']

0           Mid-range product
1           Mid-range product
2           Low-range product
3           Low-range product
4           Low-range product
                  ...
32404854    Mid-range product
32404855    Mid-range product
32404856    Low-range product
32404857    Low-range product
32404858    Low-range product
Name: price_range_loc, Length: 32404859, dtype: object

# For loops

In [22]:
ords_prods_merge['order_day_of_week'].value_counts(dropna = False)

order_day_of_week
0    6204182
1    5660230
6    4496490
2    4213830
5    4205791
3    3840534
4    3783802
Name: count, dtype: int64

In [23]:
result = []

for value in ords_prods_merge["order_day_of_week"]:
  if value == 0:
    result.append("Busiest day")
  elif value == 4:
    result.append("Least busy")
  else:
    result.append("Regularly busy")

# Busiest Day

In [24]:
ords_prods_merge['busiest_day'] = result

In [25]:
ords_prods_merge['busiest_day'].value_counts(dropna = False)

busiest_day
Regularly busy    22416875
Busiest day        6204182
Least busy         3783802
Name: count, dtype: int64

In [26]:
ords_prods_merge.head(10)

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Mid-range product,Regularly busy
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product,Regularly busy
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Low-range product,Regularly busy
5,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy
6,2398795,1,2,3,7,15.0,10258,2,0,Pistachios,117,19,3.0,both,Low-range product,Regularly busy
7,2398795,1,2,3,7,15.0,12427,3,1,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy
8,2398795,1,2,3,7,15.0,13176,4,0,Bag of Organic Bananas,24,4,10.3,both,Mid-range product,Regularly busy
9,2398795,1,2,3,7,15.0,26088,5,1,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product,Regularly busy

# Busiest Days of the Week

In [27]:
result_2 = []

for value in ords_prods_merge["order_day_of_week"]:
    if value == 0 or value == 1:  
        result_2.append("Busiest days")
    elif value == 4 or value == 3: 
        result_2.append("Slowest days")
    else: 
        result_2.append("Regularly busy")

In [28]:
ords_prods_merge['busiest_days'] = result_2

In [29]:
ords_prods_merge['busiest_days'].value_counts(dropna = False)

busiest_days
Regularly busy    12916111
Busiest days      11864412
Slowest days       7624336
Name: count, dtype: int64

In [30]:
ords_prods_merge.head(10)

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Mid-range product,Regularly busy,Regularly busy
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product,Regularly busy,Regularly busy
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Low-range product,Regularly busy,Regularly busy
5,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days
6,2398795,1,2,3,7,15.0,10258,2,0,Pistachios,117,19,3.0,both,Low-range product,Regularly busy,Slowest days
7,2398795,1,2,3,7,15.0,12427,3,1,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Slowest days
8,2398795,1,2,3,7,15.0,13176,4,0,Bag of Organic Bananas,24,4,10.3,both,Mid-range product,Regularly busy,Slowest days
9,2398795,1,2,3,7,15.0,26088,5,1,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product,Regularly busy,Slowest days

# Busiest period of the day

In [31]:
result_3 = []

for value in ords_prods_merge["order_hour_of_day"]:
    if value in [10, 11, 14, 15, 13, 12, 16, 9]: 
        result_3.append("Most orders")
    elif value in [23, 6, 0, 1, 5, 2, 4, 3]: 
        result_3.append("Fewest orders")
    else: 
        result_3.append("Average orders")

In [32]:
ords_prods_merge["busiest_period_of_day"] = result_3

In [33]:
ords_prods_merge["busiest_period_of_day"].value_counts(dropna = False)

busiest_period_of_day
Most orders       21118071
Average orders     9997651
Fewest orders      1289137
Name: count, dtype: int64

In [34]:
ords_prods_merge.head(10)

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average orders
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Mid-range product,Regularly busy,Regularly busy,Average orders
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Regularly busy,Average orders
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product,Regularly busy,Regularly busy,Average orders
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Low-range product,Regularly busy,Regularly busy,Average orders
5,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders
6,2398795,1,2,3,7,15.0,10258,2,0,Pistachios,117,19,3.0,both,Low-range product,Regularly busy,Slowest days,Average orders
7,2398795,1,2,3,7,15.0,12427,3,1,Original Beef Jerky,23,19,4.4,both,Low-range product,Regularly busy,Slowest days,Average orders
8,2398795,1,2,3,7,15.0,13176,4,0,Bag of Organic Bananas,24,4,10.3,both,Mid-range product,Regularly busy,Slowest days,Average orders
9,2398795,1,2,3,7,15.0,26088,5,1,Aged White Cheddar Popcorn,23,19,4.7,both,Low-range product,Regularly busy,Slowest days,Average orders

In [35]:
ords_prods_merge.tail(10)

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
32404849,626363,206209,12,1,12,18.0,14727,20,0,Yellow Onion,123,4,3.2,both,Low-range product,Regularly busy,Busiest days,Most orders
32404850,2977660,206209,13,1,12,7.0,24852,1,1,Banana,24,4,12.3,both,Mid-range product,Regularly busy,Busiest days,Most orders
32404851,2977660,206209,13,1,12,7.0,9405,2,1,Calcium Enriched 100% Lactose Free Fat Free Milk,91,16,11.5,both,Mid-range product,Regularly busy,Busiest days,Most orders
32404852,2977660,206209,13,1,12,7.0,16168,3,1,Large Organic Omega3 Brown Eggs,86,16,11.8,both,Mid-range product,Regularly busy,Busiest days,Most orders
32404853,2977660,206209,13,1,12,7.0,39216,4,0,Original Multigrain Spoonfuls Cereal,121,14,3.3,both,Low-range product,Regularly busy,Busiest days,Most orders
32404854,2977660,206209,13,1,12,7.0,14197,5,1,Tomato Paste,9,9,5.6,both,Mid-range product,Regularly busy,Busiest days,Most orders
32404855,2977660,206209,13,1,12,7.0,38730,6,0,Brownie Crunch High Protein Bar,3,19,5.9,both,Mid-range product,Regularly busy,Busiest days,Most orders
32404856,2977660,206209,13,1,12,7.0,31477,7,0,High Protein Bar Chunky Peanut Butter,3,19,4.2,both,Low-range product,Regularly busy,Busiest days,Most orders
32404857,2977660,206209,13,1,12,7.0,6567,8,0,Chocolate Peanut Butter Protein Bar,3,19,4.9,both,Low-range product,Regularly busy,Busiest days,Most orders
32404858,2977660,206209,13,1,12,7.0,22920,9,0,Roasted & Salted Shelled Pistachios,117,19,1.7,both,Low-range product,Regularly busy,Busiest days,Most orders

In [36]:
ords_prods_merge.shape

(32404859, 18)

In [37]:
ords_prods_merge["busiest_period_of_day"].value_counts

<bound method IndexOpsMixin.value_counts of 0           Average orders
1           Average orders
2           Average orders
3           Average orders
4           Average orders
                 ...
32404854       Most orders
32404855       Most orders
32404856       Most orders
32404857       Most orders
32404858       Most orders
Name: busiest_period_of_day, Length: 32404859, dtype: object>

In [38]:
ords_prods_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32404859 entries, 0 to 32404858
Data columns (total 18 columns):
 #   Column                 Dtype
---  ------                 -----
 0   order_id               int64
 1   user_id                int64
 2   order_number           int64
 3   order_day_of_week      int64
 4   order_hour_of_day      int64
 5   days_since_last_order  float64
 6   product_id             int64
 7   add_to_cart_order      int64
 8   reordered              int64
 9   product_name           object
 10  aisle_id               int64
 11  department_id          int64
 12  prices                 float64
 13  _merge                 category
 14  price_range_loc        object
 15  busiest_day            object
 16  busiest_days           object
 17  busiest_period_of_day  object
dtypes: category(1), float64(2), int64(10), object(5)
memory usage: 4.1+ GB

# Export

In [39]:
ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_merge_clean.pkl'))