# 1. Importing Libraries and Dataset

In [4]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [3]:
path = r'C:\Users\bhava\Documents\18.02.26_Instacart Basket Analysis'

# 2. Importing Cleaned Dataset and New Customers Dataset

In [5]:
ords_prods_merge_new = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merge_new.pkl'))

In [7]:
df_custs = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'customers.csv'), index_col = False)

In [31]:
3. # New Customer Dataset Check

df_custs.head()

,user_id,gender,state,age,date_joined,number_of_dependants,marital_status,income
0,26711,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Female,Maryland,26,1/1/2017,1,married,40374

In [11]:
df_custs.tail()

,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
206204,168073,Lisa,Case,Female,North Carolina,44,4/1/2020,1,married,148828
206205,49635,Jeremy,Robbins,Male,Hawaii,62,4/1/2020,3,married,168639
206206,135902,Doris,Richmond,Female,Missouri,66,4/1/2020,2,married,53374
206207,81095,Rose,Rollins,Female,California,27,4/1/2020,1,married,99799
206208,80148,Cynthia,Noble,Female,New York,55,4/1/2020,1,married,57095

In [12]:
df_custs.shape

(206209, 10)

In [13]:
df_custs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206209 entries, 0 to 206208
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       206209 non-null  int64
 1   First Name    194950 non-null  object
 2   Surnam        206209 non-null  object
 3   Gender        206209 non-null  object
 4   STATE         206209 non-null  object
 5   Age           206209 non-null  int64
 6   date_joined   206209 non-null  object
 7   n_dependants  206209 non-null  int64
 8   fam_status    206209 non-null  object
 9   income        206209 non-null  int64
dtypes: int64(4), object(6)
memory usage: 15.7+ MB

In [14]:
df_custs.describe()

             user_id            Age   n_dependants         income
count  206209.000000  206209.000000  206209.000000  206209.000000
mean   103105.000000      49.501646       1.499823   94632.852548
std     59527.555167      18.480962       1.118433   42473.786988
min         1.000000      18.000000       0.000000   25903.000000
25%     51553.000000      33.000000       0.000000   59874.000000
50%    103105.000000      49.000000       1.000000   93547.000000
75%    154657.000000      66.000000       3.000000  124244.000000
max    206209.000000      81.000000       3.000000  593901.000000

# 4. Data Wrangling and Data Cleaning

In [21]:
# Dropping PII details to protect the customers' privacy

In [8]:
df_custs = df_custs.drop(columns=["First Name", "Surnam"])

In [9]:
df_custs.head()

,user_id,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Female,Maryland,26,1/1/2017,1,married,40374

In [17]:
# renaming column headers for consistency

In [11]:
df_custs.rename(columns = {'Gender' : 'gender'}, inplace = True)

In [12]:
df_custs.rename(columns = {'STATE' : 'state'}, inplace = True)

In [13]:
df_custs.rename(columns = {'Age' : 'age'}, inplace = True)

In [14]:
df_custs.rename(columns = {'n_dependants' : 'number_of_dependants'}, inplace = True)

In [15]:
df_custs.rename(columns = {'fam_status' : 'marital_status'}, inplace = True)

In [16]:
df_custs.head()

,user_id,gender,state,age,date_joined,number_of_dependants,marital_status,income
0,26711,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Female,Maryland,26,1/1/2017,1,married,40374

# 5. Conducting fundamental data quality and consistency checks

In [17]:
df_custs.isnull().sum()

user_id                 0
gender                  0
state                   0
age                     0
date_joined             0
number_of_dependants    0
marital_status          0
income                  0
dtype: int64

In [18]:
df_dups= df_custs[df_custs.duplicated()]

In [19]:
df_dups

Empty DataFrame
Columns: [user_id, gender, state, age, date_joined, number_of_dependants, marital_status, income]
Index: []

### No missing values nor duplicates found in the customer data

In [20]:
df_custs.dtypes

user_id                  int64
gender                  object
state                   object
age                      int64
date_joined             object
number_of_dependants     int64
marital_status          object
income                   int64
dtype: object

### No mixed data found in the customer data

In [21]:
ords_prods_merge_new.head()

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,...,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_spend_user,spending_flag,ord_regularity_median,frequency_flag
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,...,Mid-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,...,Low-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,...,Low-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,...,Low-range product,Regularly busy,Regularly busy,Average orders,10,New customer,6.367797,Low spender,20.5,Non-frequent customer

In [22]:
ords_prods_merge_new.columns

Index(['order_id', 'user_id', 'order_number', 'order_day_of_week',
       'order_hour_of_day', 'days_since_last_order', 'product_id',
       'add_to_cart_order', 'reordered', 'product_name', 'aisle_id',
       'department_id', 'prices', 'price_range_loc', 'busiest_day',
       'busiest_days', 'busiest_period_of_day', 'max_order', 'loyalty_flag',
       'avg_spend_user', 'spending_flag', 'ord_regularity_median',
       'frequency_flag'],
      dtype='object')

In [23]:
df_custs.columns

Index(['user_id', 'gender', 'state', 'age', 'date_joined',
       'number_of_dependants', 'marital_status', 'income'],
      dtype='object')

## user_id looks like it is the key between the two sets

# Merging the two columns

##### need to firstly drop _merge column from ords_prods_merge_new

In [24]:
ords_prods_merge_new = ords_prods_merge_new.drop('_merge', axis=1)

KeyError: "['_merge'] not found in axis"

In [27]:
ords_prods_merge_new.columns

Index(['order_id', 'user_id', 'order_number', 'order_day_of_week',
       'order_hour_of_day', 'days_since_last_order', 'product_id',
       'add_to_cart_order', 'reordered', 'product_name', 'aisle_id',
       'department_id', 'prices', 'price_range_loc', 'busiest_day',
       'busiest_days', 'busiest_period_of_day', 'max_order', 'loyalty_flag',
       'avg_spend_user', 'spending_flag', 'ord_regularity_median',
       'frequency_flag'],
      dtype='object')

In [28]:
print('user_id' in ords_prods_merge_new.columns)

True

In [29]:
print('user_id' in df_custs.columns)

True

In [30]:
print(ords_prods_merge_new['user_id'].dtype)

int64

In [31]:
print(df_custs['user_id'].dtype)

int64

### Since I am running into RAM issues, I will export my datasets and retry in a new script.

In [32]:
ords_prods_merge_custs = ords_prods_merge_new.merge(df_custs, on='user_id', how='inner', indicator=True)

In [33]:
ords_prods_merge_custs.head()

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,...,ord_regularity_median,frequency_flag,gender,state,age,date_joined,number_of_dependants,marital_status,income,_merge
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,both
1,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,...,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,both
2,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,...,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,both
3,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,...,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,both
4,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,...,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,both

In [34]:
ords_prods_merge_custs.tail()

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,...,ord_regularity_median,frequency_flag,gender,state,age,date_joined,number_of_dependants,marital_status,income,_merge
32404854,2977660,206209,13,1,12,7.0,14197,5,1,Tomato Paste,...,22.0,Non-frequent customer,Female,Iowa,74,9/14/2019,3,married,137969,both
32404855,2977660,206209,13,1,12,7.0,38730,6,0,Brownie Crunch High Protein Bar,...,22.0,Non-frequent customer,Female,Iowa,74,9/14/2019,3,married,137969,both
32404856,2977660,206209,13,1,12,7.0,31477,7,0,High Protein Bar Chunky Peanut Butter,...,22.0,Non-frequent customer,Female,Iowa,74,9/14/2019,3,married,137969,both
32404857,2977660,206209,13,1,12,7.0,6567,8,0,Chocolate Peanut Butter Protein Bar,...,22.0,Non-frequent customer,Female,Iowa,74,9/14/2019,3,married,137969,both
32404858,2977660,206209,13,1,12,7.0,22920,9,0,Roasted & Salted Shelled Pistachios,...,22.0,Non-frequent customer,Female,Iowa,74,9/14/2019,3,married,137969,both

In [35]:
ords_prods_merge_custs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32404859 entries, 0 to 32404858
Data columns (total 31 columns):
 #   Column                 Dtype
---  ------                 -----
 0   order_id               int64
 1   user_id                int64
 2   order_number           int64
 3   order_day_of_week      int64
 4   order_hour_of_day      int64
 5   days_since_last_order  float64
 6   product_id             int64
 7   add_to_cart_order      int64
 8   reordered              int64
 9   product_name           object
 10  aisle_id               int64
 11  department_id          int64
 12  prices                 float64
 13  price_range_loc        object
 14  busiest_day            object
 15  busiest_days           object
 16  busiest_period_of_day  object
 17  max_order              int64
 18  loyalty_flag           object
 19  avg_spend_user         float64
 20  spending_flag          object
 21  ord_regularity_median  float64
 22  frequency_flag         object
 23  gender                 object
 24  state                  object
 25  age                    int64
 26  date_joined            object
 27  number_of_dependants   int64
 28  marital_status         object
 29  income                 int64
 30  _merge                 category
dtypes: category(1), float64(4), int64(14), object(12)
memory usage: 7.3+ GB

In [36]:
ords_prods_merge_custs.describe()

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_last_order,product_id,add_to_cart_order,reordered,aisle_id,department_id,prices,max_order,avg_spend_user,ord_regularity_median,age,number_of_dependants,income
count,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.032876e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.240486e+07,3.239973e+07,3.240486e+07,3.240486e+07,3.240485e+07,3.240486e+07,3.240486e+07,3.240486e+07
mean,1.710745e+06,1.029372e+05,1.714230e+01,2.738867e+00,1.342515e+01,1.110408e+01,2.559866e+04,8.352547e+00,5.895873e-01,7.119612e+01,9.919792e+00,7.790994e+00,3.305217e+01,1.198023e+01,1.039776e+01,4.946527e+01,1.501896e+00,9.943773e+04
std,9.872988e+05,5.946610e+04,1.753532e+01,2.090077e+00,4.246380e+00,8.779064e+00,1.408400e+04,7.127071e+00,4.919087e-01,3.821139e+01,6.281485e+00,4.241809e+00,2.515525e+01,8.324227e+01,7.131754e+00,1.848558e+01,1.118865e+00,4.305727e+04
min,2.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.800000e+01,0.000000e+00,2.590300e+04
25%,8.559470e+05,5.142200e+04,5.000000e+00,1.000000e+00,1.000000e+01,5.000000e+00,1.354400e+04,3.000000e+00,0.000000e+00,3.100000e+01,4.000000e+00,4.200000e+00,1.300000e+01,7.387298e+00,6.000000e+00,3.300000e+01,1.000000e+00,6.700400e+04
50%,1.711049e+06,1.026160e+05,1.100000e+01,3.000000e+00,1.300000e+01,8.000000e+00,2.530200e+04,6.000000e+00,1.000000e+00,8.300000e+01,9.000000e+00,7.400000e+00,2.600000e+01,7.824786e+00,8.000000e+00,4.900000e+01,2.000000e+00,9.661800e+04
75%,2.565499e+06,1.543890e+05,2.400000e+01,5.000000e+00,1.600000e+01,1.500000e+01,3.794700e+04,1.100000e+01,1.000000e+00,1.070000e+02,1.600000e+01,1.130000e+01,4.700000e+01,8.254023e+00,1.300000e+01,6.500000e+01,3.000000e+00,1.279120e+05
max,3.421083e+06,2.062090e+05,9.900000e+01,6.000000e+00,2.300000e+01,3.000000e+01,4.968800e+04,1.450000e+02,1.000000e+00,1.340000e+02,2.100000e+01,2.500000e+01,9.900000e+01,2.500542e+04,3.000000e+01,8.100000e+01,3.000000e+00,5.939010e+05

In [37]:
ords_prods_merge_custs.shape

(32404859, 31)

## Exporting Data

In [63]:
ords_prods_merge_new.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_merge_new.pkl'))

In [64]:
df_custs.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'customers.pkl'))

# Exporting Data with Customers Dataset merged as a pickle file

In [38]:
ords_prods_merge_custs.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'ords_prods_merge_custs.pkl'))