# Import libraries

In [3]:
import pandas as pd
import numpy as np
import os

In [4]:
path = r'C:\Users\bhava\Documents\18.02.26_Instacart Basket Analysis'

In [5]:
path

'C:\\Users\\bhava\\Documents\\18.02.26_Instacart Basket Analysis'

# Importing dataset folders

--- df_ords = pd.read_csv(os.path.join(path, '02 Data', 'Prepared Data', 'orders_wrangled.csv'), index_col = False)

In [8]:
# Define a dictionary containing January 2020 data
data1 = {'customer_id':['6732', '767', '890', '635'],
    'month':['Jan-20', 'Jan-20', 'Jan-20', 'Jan-20'],
    'purchased_meat':[0, 13, 3, 4],
    'purchased_alcohol':[1, 2, 10, 0],
    'purchased_snacks':[10, 5, 1, 7]}

In [9]:
# Define a dictionary containing February 2020 data
data2 = {'customer_id':['6732', '767', '890', '635'],
    'month':['Feb-20', 'Feb-20', 'Feb-20', 'Feb-20'],
    'purchased_meat':[0, 10, 5, 3],
    'purchased_alcohol':[2, 4, 14, 0],
    'purchased_snacks':[15, 3, 2, 6]}

In [10]:
#Convert the dictionary into dataframe
df = pd.DataFrame(data1,index=[0, 1, 2, 3])

In [11]:
df_1 = pd.DataFrame(data2,index=[0, 1, 2, 3])

In [12]:
df

  customer_id   month  purchased_meat  purchased_alcohol  purchased_snacks
0        6732  Jan-20               0                  1                10
1         767  Jan-20              13                  2                 5
2         890  Jan-20               3                 10                 1
3         635  Jan-20               4                  0                 7

In [13]:
df_1

  customer_id   month  purchased_meat  purchased_alcohol  purchased_snacks
0        6732  Feb-20               0                  2                15
1         767  Feb-20              10                  4                 3
2         890  Feb-20               5                 14                 2
3         635  Feb-20               3                  0                 6

#  first create a list—frames—containing the dataframes you want to combine

In [16]:
frames = [df, df_1]

# Concatenating Data

In [17]:
df_concat = pd.concat(frames)

In [18]:
df_concat

  customer_id   month  purchased_meat  purchased_alcohol  purchased_snacks
0        6732  Jan-20               0                  1                10
1         767  Jan-20              13                  2                 5
2         890  Jan-20               3                 10                 1
3         635  Jan-20               4                  0                 7
0        6732  Feb-20               0                  2                15
1         767  Feb-20              10                  4                 3
2         890  Feb-20               5                 14                 2
3         635  Feb-20               3                  0                 6

####  This is the axis argument. Remember that the default setting for pd.concat() is to stack any new rows after the existing ones (creating a long-format dataframe). The argument for this is axis = 0, but since this is the default, you don’t need to specify it. If, however, you wanted to place the two dataframes side by side (creating a wide-format dataframe), you’d need to use a different argument: axis = 1.

In [19]:
df_concat = pd.concat(frames, axis = 1)

In [20]:
df_concat

,customer_id,month,purchased_meat,purchased_alcohol,purchased_snacks,customer_id,month,purchased_meat,purchased_alcohol,purchased_snacks
0,6732,Jan-20,0,1,10,6732,Feb-20,0,2,15
1,767,Jan-20,13,2,5,767,Feb-20,10,4,3
2,890,Jan-20,3,10,1,890,Feb-20,5,14,2
3,635,Jan-20,4,0,7,635,Feb-20,3,0,6

##### the pd.concat() function:

Is suitable for rows or columns of the same length.
Will place dataframes on top of each other by default (axis = 0).
Requires a list as its main argument (this is why the frames list was created first in the example above).

## Concatenating data is also known as “setting” data in other languages like SAS. While we won’t be using the term “set” in this course, it can be good to know what this means in case you see others use it online or later on in your career.

## Joining Data

###### The df.join() function is typically only used in cases where your index column carries some sort of information (rather than simply displaying the number of rows)

# Merging Data

##### The best use cases for the df.merge() function are those where the dataframes you want to combine don’t match in shape—different from concatenate. In these cases, you’ll need a key or some kind of common identifier column that brings the two (or more) data sets together.

In [21]:
data3 = {'customer_id':['6732', '767', '890', '635'],
    'month':['Jan-20', 'Jan-20', 'Jan-20', 'Jan-20'],
    'days_purchased_on':[0, 10, 4, 1]}

In [22]:
df_2 = pd.DataFrame(data3,index=[0, 1, 2, 3])

In [23]:
df_merged = df.merge(df_2, on = 'customer_id')

In [24]:
df_merged

,customer_id,month_x,purchased_meat,purchased_alcohol,purchased_snacks,month_y,days_purchased_on
0,6732,Jan-20,0,1,10,Jan-20,0
1,767,Jan-20,13,2,5,Jan-20,10
2,890,Jan-20,3,10,1,Jan-20,4
3,635,Jan-20,4,0,7,Jan-20,1

# In case you want two keys, you can use:

df_merged = df.merge(df_2, on 0 = ['customer_id', 'month'])

Note here the syntax for using multiple columns as keys during a merge. The columns are included in the form of a list inside square brackets within the on argument. This is necessary when including multiple parameters within a single argument. Multiple arguments within a single function are separated by commas, but multiple parameters within a single argument need to be set off in brackets. If you don’t include the brackets and simply offset your parameters with commas (df.merge(df_2, on = 'customer_id', 'month')), pandas will think these are additional arguments, resulting in errors.

In [27]:
df_merged2 = df.merge(df_2, on = ['customer_id', 'month'])

In [28]:
df_merged2

,customer_id,month,purchased_meat,purchased_alcohol,purchased_snacks,days_purchased_on
0,6732,Jan-20,0,1,10,0
1,767,Jan-20,13,2,5,10
2,890,Jan-20,3,10,1,4
3,635,Jan-20,4,0,7,1

###### A quick and easy way to check for a full match is via the indicator = True argument.

In [29]:
df_merged = df.merge(df_2, on = ['customer_id', 'month'], indicator = True)

In [30]:
df_merged

,customer_id,month,purchased_meat,purchased_alcohol,purchased_snacks,days_purchased_on,_merge
0,6732,Jan-20,0,1,10,0,both
1,767,Jan-20,13,2,5,10,both
2,890,Jan-20,3,10,1,4,both
3,635,Jan-20,4,0,7,1,both

In [32]:
df_merged['_merge'].value_counts()

_merge
both          4
left_only     0
right_only    0
Name: count, dtype: int64

####  “_merge” column (also referred to as a “merge flag”)

#  remember to make new dataframes when running procedures like this so that you don’t overwrite any data that might be necessary later.

#### Test merge without overwriting

In [33]:
pd.merge(df,df_2, on = ['customer_id', 'month'], indicator = True)

,customer_id,month,purchased_meat,purchased_alcohol,purchased_snacks,days_purchased_on,_merge
0,6732,Jan-20,0,1,10,0,both
1,767,Jan-20,13,2,5,10,both
2,890,Jan-20,3,10,1,4,both
3,635,Jan-20,4,0,7,1,both